version: '3.9'

services:
  api:
    build:
      context: src/api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - ./src/api/.env
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${API_LOCAL_PORT}:8000"
    volumes:
      - ./docker-config/php.ini:/usr/local/etc/php/php.ini
      - ./src/api:/app/api
    depends_on:
      - database
    networks:
      - app

  web:
    build:
      context: src/web
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    env_file:
      - ./src/api/.env
    ports:
      - "${WEB_LOCAL_PORT}:3000"
    volumes:
      - ./src/web:/app/web
    depends_on:
      - api
    networks:
      - app

  database:
    container_name: database
    image: mysql:8.0.31
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - ./src/api/.env
    ports:
      - "${DB_LOCAL_PORT}:3306"
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  app:
    driver: bridge
    name: ${PROJECT_NAME}_app


volumes:
  mysql-volume:
    driver: local
